### ISSUE TITLE
Reference vs Expected path?

### ISSUE THREAD

**Issue by keithgmitchell** [RosettaCommons/DeepAb#23]
Downloaded the tar wheel and ran`sudo python setup.py install` and get the following?

```

>>> import pyrosetta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/trimmer_lab/lib/python3.8/site-packages/pyrosetta/__init__.py", line 15, in <module>
    import pyrosetta.rosetta as rosetta
ImportError: dlopen(/opt/anaconda3/envs/trimmer_lab/lib/python3.8/site-packages/pyrosetta/rosetta.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /opt/anaconda3/envs/trimmer_lab/lib/python3.8/site-packages/pyrosetta/rosetta.so (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib


```

**Comment by roccomoretti** [comment]
It looks like there's an issue with your PyRosetta installation. Which version of PyRosetta did you install (how did you install PyRosetta)? What's the Mac OS version on the machine you are running on?

**Comment by keithgmitchell** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/36057349/195163376-93403d14-cb1b-4ee8-90ca-5961ea509c09.png">
And I had 328 here: https://west.rosettacommons.org/pyrosetta/release/release/PyRosetta4.MinSizeRel.python38.mac/

**Comment by lyskov** [comment]
@keithgmitchell looks like this PyRosetta build might require macOS Monterey to run. I would recommend to try to downloading one of the previous builds, say ~< 300 and see if that makes a difference. (note that you can also install PyRosetta directly thorough Conda)

**Comment by lyskov** [comment]
You should be able to grab release 305 here https://west.rosettacommons.org/pyrosetta/release/release/PyRosetta4.Release.python38.mac/ (use your PyRosetta login and pass) which i think should be able to run on Catalina
